### ISSUE TITLE
OMG!

### ISSUE THREAD

**Issue by MehmetKaranlik** [VB10/refactor_flutter_aps#1]
Bir an projenin amacını anlamadım.
degistirColor hehe :)

**Comment by VB10** [comment]
pr a bide akşam videoya bak anlarsın 😘

**Comment by VB10** [comment]
her gecenin bir sabahi vardir komiser
![image](https://user-images.githubusercontent.com/17102578/145959331-ecf63ed0-8ee9-45d6-abf0-48b456ebc6f4.png)

**Comment by MehmetKaranlik** [comment]
Before refactoring
![Ekran Resmi 2021-12-14 11 28 17](https://user-images.githubusercontent.com/89414084/145961192-50b7a974-8bac-4008-b249-d2e0f12aa151.png)
After refactoring
![Ekran Resmi 2021-12-14 11 28 27](https://user-images.githubusercontent.com/89414084/145961274-61278572-a24b-46c3-bdf5-7137fd965c98.png)
